## 가설 설정
### 1.성별(Gender)에 따른 가설
- H0 : 고객의 성별은 Info 쿠폰의 최종 결제 전환율에 영향을 주지 않는다.
- H1 : 고객의 성별에 따라 Info 쿠폰의 최종 결제 전환율에 유의미한 차이가 있다.

### 2.나이(Age)에 따른 가설
- H0 : 연령대는 Info 쿠폰 전환율에 영향을 주지 않는다.
- H1 : 연령대는 Info 쿠폰 전환율에 유의미한 차이가 있다.

### 3.소득수준(Income)에 따른 가설
- H0 : 소득 수준은 Info 쿠폰에 대한 전환율과 관계가 없다.
- H1 : 소득 수준은 Info 쿠폰 전환율에 유의미한 영향을 미친다.

In [24]:
import pandas as pd
import numpy as np
from scipy.stats import chi2_contingency
from scipy.stats.contingency import association

info_demo = pd.read_csv('../data/info_demo.csv')

In [4]:
info_demo

,person,offer_id,offer_cycle,duration,offer received,offer viewed,expire_time,age,gender,income,age_group,income_group,is_viewed,is_converted
0,0009655768c64bdeb2e877511632db8f,informational_0_0_3,1,3.0,168.0,192.0,240.0,33.0,M,72000.0,30대,6만~8만,1,1
1,0009655768c64bdeb2e877511632db8f,informational_0_0_4,1,4.0,336.0,372.0,432.0,33.0,M,72000.0,30대,6만~8만,1,1
2,0011e0d4e6b944f998e987f904e8c1e5,informational_0_0_3,1,3.0,336.0,354.0,408.0,40.0,O,57000.0,40대,4만~6만,1,0
3,0011e0d4e6b944f998e987f904e8c1e5,informational_0_0_4,1,4.0,0.0,6.0,96.0,40.0,O,57000.0,40대,4만~6만,1,0
4,0020c2b971eb4e9188eac86d93036a77,informational_0_0_3,1,3.0,504.0,660.0,576.0,59.0,F,90000.0,50대,8만~10만,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15230,fff0f0aac6c547b9b263080f09a5586a,informational_0_0_4,2,4.0,576.0,636.0,672.0,67.0,M,80000.0,60대 이상,6만~8만,1,1
15231,fff3ba4757bd42088c044ca26d73817a,informational_0_0_3,1,3.0,336.0,NaN,408.0,69.0,F,83000.0,60대 이상,8만~10만,0,0
15232,fff3ba4757bd42088c044ca26d73817a,informational_0_0_3,2,3.0,504.0,540.0,576.0,69.0,F,83000.0,60대 이상,8만~10만,1,1
15233,fff8957ea8b240a6b5e634b6ee8eafcf,informational_0_0_4,1,4.0,504.0,NaN,600.0,71.0,M,56000.0,60대 이상,4만~6만,0,0
15234,fffad4f4828548d1b5583907f2e9906b,informational_0_0_3,1,3.0,168.0,168.0,240.0,34.0,M,34000.0,30대,4만 미만,1,1

In [17]:
# 성별에 따른 가설 검정 시작

target_gender_df = info_demo[info_demo['gender'].isin(['M', 'F'])] # M과 F만 

contingency_table_gender = pd.crosstab(target_gender_df['gender'], target_gender_df['is_converted']) 
# is_converted(0) : 구매까지 이어지지 못함. is_converted(1) : 구매까지 이어짐. 
print("[성별 교차표]")
display(contingency_table_gender)

# 카이제곱 검정
chi2_gender, p_val_gender, dof_gender, expected_gender = chi2_contingency(contingency_table_gender)
print(f"카이제곱 통계량 : {chi2_gender:.4f}")
print(f"p-value: {p_val_gender:.4f}")
print(f"자유도: {dof_gender}")
print('\n')

# 최종 결론
if p_val_gender < 0.05:
    print(f"결론 : p-value({p_val_gender:.4f})가 0.05보다 작으므로 귀무가설 기각")
    print("해석: 성별에 따라 Informational 쿠폰 전환율에 통계적으로 유의미한 차이가 있다.")
else:
    print(f"결론 : p-value({p_val_gender:.4f})가 0.05 이상이므로 귀무가설을 기각하지 못한다")
    print("해석: 성별에 따른 Informational 쿠폰 전환율이 통계적으로 유의미하지 않다.")

[성별 교차표]

is_converted     0     1
gender
F             3401  2137
M             4536  3031

카이제곱 통계량 : 2.8224
p-value: 0.0930
자유도: 1


결론 : p-value(0.0930)가 0.05 이상이므로 귀무가설을 기각하지 못한다
해석: 성별에 따른 Informational 쿠폰 전환율이 통계적으로 유의미하지 않다.

In [37]:
# 연령대별 가설 검정 시작

target_age_df = info_demo[info_demo['age_group'] != 'Unknown']

contingency_table_age = pd.crosstab(target_age_df['age_group'], target_age_df['is_converted'])
# is_converted(0) : 구매까지 이어지지 못함. is_converted(1) : 구매까지 이어짐. 
print("[연령대별 교차표]")
display(contingency_table_age)

# 카이제곱 검정
chi2_age, p_val_age, dof_age, expected_age = chi2_contingency(contingency_table_age)
print(f"카이제곱 통계량 : {chi2_age:.4f}")
print(f"p-value: {p_val_age:.4e}")
print(f"자유도: {dof_age}")
print('\n')

# 최종 결론
if p_val_age < 0.05:
    print(f"결론 : p-value({p_val_age:.4e})가 0.05보다 작으므로 귀무가설 기각")
    print("해석: 연령대에 따라 Informational 쿠폰 전환율에 통계적으로 유의미한 차이가 있다.")
else:
    print(f"결론 : p-value({p_val_age:.4e})가 0.05 이상이므로 귀무가설을 기각하지 못한다")
    print("해석: 연령대에 따른 Informational 쿠폰 전환율이 통계적으로 유의미하지 않다.")


# 효과크기(Cramer's V)
print("="*80)
print("[효과크기 (Cramer's V)]")
v_score = association(contingency_table_age.values, method='cramer')
print(f"소득수준 전환율 차이의 효과 크기 : {v_score:.4f}")


if v_score < 0.10:
    print(f" 해석 : 효과크기가 'small' 미만이다. (통계적으로 유의미하나 실질적 차이는 매우 미미)")
elif v_score < 0.30:
    print(f" 해석 : 효과크기가 'small' (작은 연관성)")
elif v_score < 0.50:
    print(f" 해석 : 효과크기가 'Medium' (중간 수준의 연관성)")
else:
    print(f" 해석 : 효과크기가 'Large' (큰 연관성)")
    

# 조정된 잔차 분석
print("="*80)
print("[조정된 잔차 분석]")
observed = contingency_table_age.values
N = observed.sum()
row_sums = observed.sum(axis=1, keepdims=True) # R_i
col_sums = observed.sum(axis=0, keepdims=True) # C_j
adjusted_residuals = (observed - expected_age) / np.sqrt(expected_age * (1 - row_sums / N) * (1 - col_sums / N))

# 출력
adj_res_df = pd.DataFrame(
    adjusted_residuals,
    index=contingency_table_age.index,
    columns=contingency_table_age.columns
)
display(adj_res_df)

[연령대별 교차표]

is_converted     0     1
age_group
10대 이하         109    90
20대            698   479
30대            767   611
40대           1199   848
50대           1943  1259
60대 이상        3332  1965

카이제곱 통계량 : 32.9718
p-value: 3.8123e-06
자유도: 5


결론 : p-value(3.8123e-06)가 0.05보다 작으므로 귀무가설 기각
해석: 연령대에 따라 Informational 쿠폰 전환율에 통계적으로 유의미한 차이가 있다.
================================================================================
[효과크기 (Cramer's V)]
소득수준 전환율 차이의 효과 크기 : 0.0498
 해석 : 효과크기가 'small' 미만이다. (통계적으로 유의미하나 실질적 차이는 매우 미미)
================================================================================
[조정된 잔차 분석]

is_converted         0         1
age_group
10대 이하       -1.668250  1.668250
20대          -0.887991  0.887991
30대          -3.890842  3.890842
40대          -1.949822  1.949822
50대           0.225244 -0.225244
60대 이상        4.591627 -4.591627

### 조정된 잔차 분석 해석
- is_converted = 1 열만 보면 됨!
- 잔차가 -2보다 작은 그룹 : 기대보다 결제를 하지 않는다. => 단순 알림을 보낼 필요가 없음
- 잔차가 +2보다 큰 그룹 : 기대보다 결제까지 잘 이어지는 타겟층 => 알림 핵심 타겟층
- 잔차가 -2 ~ +2 그룹 : 평범

In [ ]:
# 수익별 가설 검정 시작

target_income_df = info_demo[info_demo['income_group'] != 'Unknown']

contingency_table_income = pd.crosstab(target_income_df['income_group'], target_income_df['is_converted'])
# is_converted(0) : 구매까지 이어지지 못함. is_converted(1) : 구매까지 이어짐. 
print("[소득수준별 교차표]")
display(contingency_table_income)

# 카이제곱 검정
chi2_income, p_val_income, dof_income, expected_income = chi2_contingency(contingency_table_income)
print(f"카이제곱 통계량 : {chi2_income:.4f}")
print(f"p-value: {p_val_income:.4e}")
print(f"자유도: {dof_income}")

# 최종 결론
if p_val_income < 0.05:
    print(f"결론 : p-value({p_val_income:.4e})가 0.05보다 작으므로 귀무가설 기각")
    print("해석: 소득수준에 따라 Informational 쿠폰 전환율에 통계적으로 유의미한 차이가 있다.")
else:
    print(f"결론 : p-value({p_val_income:.4e})가 0.05 이상이므로 귀무가설을 기각하지 못한다")
    print("해석: 소득수준에 따른 Informational 쿠폰 전환율이 통계적으로 유의미하지 않다.")

# 효과크기(Cramer's V)
print("="*80)
print("[효과크기 (Cramer's V)]")
v_score = association(contingency_table_income.values, method='cramer')
print(f"소득수준 전환율 차이의 효과 크기 : {v_score:.4f}")


if v_score < 0.10:
    print(f" 해석 : 효과크기가 'small' 미만이다. (통계적으로 유의미하나 실질적 차이는 매우 미미)")
elif v_score < 0.30:
    print(f" 해석 : 효과크기가 'small' (작은 연관성)")
elif v_score < 0.50:
    print(f" 해석 : 효과크기가 'Medium' (중간 수준의 연관성)")
else:
    print(f" 해석 : 효과크기가 'Large' (큰 연관성)")
    

# 조정된 잔차 분석
print("="*80)
print("[조정된 잔차 분석]")
observed = contingency_table_income.values
N = observed.sum()
row_sums = observed.sum(axis=1, keepdims=True) # R_i
col_sums = observed.sum(axis=0, keepdims=True) # C_j
adjusted_residuals = (observed - expected_income) / np.sqrt(expected_income * (1 - row_sums / N) * (1 - col_sums / N))

# 출력
adj_res_df = pd.DataFrame(
    adjusted_residuals,
    index=contingency_table_income.index,
    columns=contingency_table_income.columns
)
display(adj_res_df)

[소득수준별 교차표]

is_converted     0     1
income_group
10만 이상         694   195
4만 미만         1100   779
4만~6만         2376  1789
6만~8만         2390  1683
8만~10만        1488   806

카이제곱 통계량 : 162.5306
p-value: 4.1893e-34
자유도: 4
결론 : p-value(4.1893e-34)가 0.05보다 작으므로 귀무가설 기각
해석: 소득수준에 따라 Informational 쿠폰 전환율에 통계적으로 유의미한 차이가 있다.
================================================================================
[효과크기 (Cramer's V)]
소득수준 전환율 차이의 효과 크기 : 0.1105
 해석 : 효과크기가 'small' (작은 연관성)
================================================================================
[조정된 잔차 분석]

is_converted          0          1
income_group
10만 이상        11.083931 -11.083931
4만 미만         -1.884684   1.884684
4만~6만         -5.518993   5.518993
6만~8만         -2.871867   2.871867
8만~10만         4.689216  -4.689216

### 조정된 잔차 분석 해석
- is_converted = 1 열만 보면 됨!
- 잔차가 -2보다 작은 그룹 : 기대보다 결제를 하지 않는다. => 단순 알림을 보낼 필요가 없음
- 잔차가 +2보다 큰 그룹 : 기대보다 결제까지 잘 이어지는 타겟층 => 알림 핵심 타겟층
- 잔차가 -2 ~ +2 그룹 : 평범

# 최종 인사이트 뼈대 with 무아튜터님
- 소득수준이 전환 여부에 통계적으로 유의한 영향을 미치지만, 전체적인 영향력 자체는 크지 않다.
- 그리고 조정된 잔차 분석을 통해 특정 소득 구간에서의 전환 패턴 차이를 말씀하시면 될 것 같아요~

| 조정된 잔차 값   | 해석                                              |
|------------------|---------------------------------------------------|
| \|잔차\| > 2     | 해당 범주/셀이 기대빈도와 유의하게 다릅니다        |
| \|잔차\| ≤ 2     | 해당 범주/셀은 기대빈도와 유의한 차이가 없습니다   |
| 잔차 > 0 (양수)  | 기대보다 **많이** 관측됨                           |
| 잔차 < 0 (음수)  | 기대보다 **적게** 관측됨                           |

**실무 팁**: 
- 범주형에서는 Cramér's V보다 **조정된 잔차 분석**(어느 셀이 기대와 다른가)이 실질적으로 더 중요합니다.

Next Step)
전환율말고 금액으로
profit or amount