In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from IPython.display import display
import warnings

warnings.filterwarnings('ignore')

# 한글 폰트 설정
plt.rcParams['font.family'] = 'Malgun Gothic'

# 마이너스 기호 깨짐 방지
plt.rcParams['axes.unicode_minus'] = False

# 전역 시드 설정 (재현성을 위해)
np.random.seed(42)

print("="*60)
print("라이브러리 로드 완료!")
print("한글 폰트 설정 완료!")
print("="*60)

============================================================
라이브러리 로드 완료!
한글 폰트 설정 완료!
============================================================

---

In [3]:
df_pf = pd.read_csv('../data/portfolio.csv')
df_pro = pd.read_csv('../data/profile.csv')
df_tran = pd.read_csv('../data/transcript.csv')

In [4]:
def check(df, name="Data"):
    print(f"{name} 기본 정보")
    
    print("\n[1] 데이터 크기")
    display(df.shape)
    
    print("\n[2] 컬럼 정보")
    df.info()
    
    print("\n[3] 결측치 개수")
    display(
    df.isnull().sum()
    .sort_values(ascending=False)
    .to_frame("결측치 개수")
    )
    
    print("\n[4] 중복 데이터 개수")
    display(df.duplicated().sum())

---

# 1. portfolio.csv

In [5]:
check(df_pf, 'portfolio.csv')

portfolio.csv 기본 정보

[1] 데이터 크기

(10, 7)

[2] 컬럼 정보
<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  10 non-null     int64
 1   reward      10 non-null     int64
 2   channels    10 non-null     str
 3   difficulty  10 non-null     int64
 4   duration    10 non-null     int64
 5   offer_type  10 non-null     str
 6   id          10 non-null     str
dtypes: int64(4), str(3)
memory usage: 692.0 bytes

[3] 결측치 개수

            결측치 개수
Unnamed: 0       0
reward           0
channels         0
difficulty       0
duration         0
offer_type       0
id               0

[4] 중복 데이터 개수

np.int64(0)

In [6]:
df_pf.describe()

       Unnamed: 0     reward  difficulty   duration
count    10.00000  10.000000   10.000000  10.000000
mean      4.50000   4.200000    7.700000   6.500000
std       3.02765   3.583915    5.831905   2.321398
min       0.00000   0.000000    0.000000   3.000000
25%       2.25000   2.000000    5.000000   5.000000
50%       4.50000   4.000000    8.500000   7.000000
75%       6.75000   5.000000   10.000000   7.000000
max       9.00000  10.000000   20.000000  10.000000

In [7]:
df_pf.head()

,Unnamed: 0,reward,channels,difficulty,duration,offer_type,id
0,0,10,"['email', 'mobile', 'social']",10,7,bogo,ae264e3637204a6fb9bb56bc8210ddfd
1,1,10,"['web', 'email', 'mobile', 'social']",10,5,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
2,2,0,"['web', 'email', 'mobile']",0,4,informational,3f207df678b143eea3cee63160fa8bed
3,3,5,"['web', 'email', 'mobile']",5,7,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
4,4,5,"['web', 'email']",20,10,discount,0b1e1539f2cc45b7b9fa7c272da2e1d7

---

# 2. profile.csv

In [8]:
check(df_pro, 'profile.csv')

profile.csv 기본 정보

[1] 데이터 크기

(17000, 6)

[2] 컬럼 정보
<class 'pandas.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        17000 non-null  int64
 1   gender            14825 non-null  str
 2   age               17000 non-null  int64
 3   id                17000 non-null  str
 4   became_member_on  17000 non-null  int64
 5   income            14825 non-null  float64
dtypes: float64(1), int64(3), str(2)
memory usage: 797.0 KB

[3] 결측치 개수

                  결측치 개수
gender              2175
income              2175
Unnamed: 0             0
age                    0
id                     0
became_member_on       0

[4] 중복 데이터 개수

np.int64(0)

In [9]:
df_pro.describe()

         Unnamed: 0           age  became_member_on         income
count  17000.000000  17000.000000      1.700000e+04   14825.000000
mean    8499.500000     62.531412      2.016703e+07   65404.991568
std     4907.621624     26.738580      1.167750e+04   21598.299410
min        0.000000     18.000000      2.013073e+07   30000.000000
25%     4249.750000     45.000000      2.016053e+07   49000.000000
50%     8499.500000     58.000000      2.017080e+07   64000.000000
75%    12749.250000     73.000000      2.017123e+07   80000.000000
max    16999.000000    118.000000      2.018073e+07  120000.000000

In [10]:
df_pro.head()

,Unnamed: 0,gender,age,id,became_member_on,income
0,0,NaN,118,68be06ca386d4c31939f3a4f0e3dd783,20170212,NaN
1,1,F,55,0610b486422d4921ae7d2bf64640c50b,20170715,112000.0
2,2,NaN,118,38fe809add3b4fcf9315a9694bb96ff5,20180712,NaN
3,3,F,75,78afa995795e4d85b5d9ceeca43f5fef,20170509,100000.0
4,4,NaN,118,a03223e636434f42ac4c3df47e8bac43,20170804,NaN

---

# 3. transcript.csv

In [11]:
check(df_tran, 'transcript.csv')

transcript.csv 기본 정보

[1] 데이터 크기

(306534, 5)

[2] 컬럼 정보
<class 'pandas.DataFrame'>
RangeIndex: 306534 entries, 0 to 306533
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  306534 non-null  int64
 1   person      306534 non-null  str
 2   event       306534 non-null  str
 3   value       306534 non-null  str
 4   time        306534 non-null  int64
dtypes: int64(2), str(3)
memory usage: 11.7 MB

[3] 결측치 개수

            결측치 개수
Unnamed: 0       0
person           0
event            0
value            0
time             0

[4] 중복 데이터 개수

np.int64(0)

In [12]:
df_tran.describe()

          Unnamed: 0           time
count  306534.000000  306534.000000
mean   153266.500000     366.382940
std     88488.888045     200.326314
min         0.000000       0.000000
25%     76633.250000     186.000000
50%    153266.500000     408.000000
75%    229899.750000     528.000000
max    306533.000000     714.000000

In [13]:
df_tran.head()

,Unnamed: 0,person,event,value,time
0,0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0
1,1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0
2,2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0
3,3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0
4,4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0