성별 x 쿠폰타입 전환율
연령대 x 쿠폰타입 평균 결제액
소득 구간 x 쿠폰타입 달성률
멤버십 가입 연도 x 쿠폰타입 반응률 (오래된 고객 vs 신규 고객)

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from IPython.display import display
import warnings

import ast

warnings.filterwarnings('ignore')

# 한글 폰트 설정
plt.rcParams['font.family'] = 'Malgun Gothic'

# 마이너스 기호 깨짐 방지
plt.rcParams['axes.unicode_minus'] = False

# 전역 시드 설정 (재현성을 위해)
np.random.seed(42)

print("="*60)
print("라이브러리 로드 완료!")
print("한글 폰트 설정 완료!")
print("="*60)

============================================================
라이브러리 로드 완료!
한글 폰트 설정 완료!
============================================================

In [2]:
portfolio = pd.read_csv('../1data/portfolio.csv')
profile = pd.read_csv('../1data/profile.csv')
transcript = pd.read_csv('../1data/transcript.csv')

merged = pd.read_csv('../1data/all_merged.csv')
promotion = pd.read_csv('../1data/promotion_df.csv')
normal = pd.read_csv('../1data/normal_flow_df.csv')

---

In [14]:
promotion.head()

,person,offer_id,offer_cycle,offer received,offer viewed,offer completed,transcript_reward,offer_type,difficulty,reward,...,mobile,social,gender,age,became_member_on,income,amount,is_received,is_viewed,is_completed
0,0009655768c64bdeb2e877511632db8f,bogo_5_5_5,Bogo_1,408.0,456.0,414.0,5.0,bogo,5,5,...,1,1,M,33,2017-04-21,72000.0,8.57,1,1,1
1,0009655768c64bdeb2e877511632db8f,discount_10_2_10,Discount_1,504.0,540.0,528.0,2.0,discount,10,2,...,1,1,M,33,2017-04-21,72000.0,14.11,1,1,1
2,0009655768c64bdeb2e877511632db8f,discount_10_2_7,Discount_1,576.0,NaN,576.0,2.0,discount,10,2,...,1,0,M,33,2017-04-21,72000.0,10.27,1,0,1
3,0009655768c64bdeb2e877511632db8f,informational_0_0_3,Informational_1,168.0,192.0,NaN,NaN,informational,0,0,...,1,1,M,33,2017-04-21,72000.0,NaN,1,1,0
4,0009655768c64bdeb2e877511632db8f,informational_0_0_4,Informational_1,336.0,372.0,NaN,NaN,informational,0,0,...,1,0,M,33,2017-04-21,72000.0,NaN,1,1,0

---

# 고객 전체 흐름

## 1. 성별x구폰타입 전환율

In [4]:
# bogo, discount만 필터링
bd_df = promotion[promotion['offer_type'].isin(['bogo', 'discount'])].copy()

# 성별 x offer_type 퍼널 전환율
gender_funnel = (
    bd_df
    .groupby(['gender', 'offer_type'])
    .agg(
        received=('is_received', 'sum'),
        viewed=('is_viewed', 'sum'),
        completed=('is_completed', 'sum')
    )
    .reset_index()
)
gender_funnel['viewed_rate'] = (gender_funnel['viewed'] / gender_funnel['received'] * 100).round(2)
gender_funnel['completed_rate'] = (gender_funnel['completed'] / gender_funnel['viewed'] * 100).round(2)
gender_funnel['total_rate'] = (gender_funnel['completed'] / gender_funnel['received'] * 100).round(2)
display(gender_funnel)

# 성별 x offer_id 퍼널 전환율
gender_funnel_id = (
    bd_df
    .groupby(['gender', 'offer_id'])
    .agg(
        received=('is_received', 'sum'),
        viewed=('is_viewed', 'sum'),
        completed=('is_completed', 'sum')
    )
    .reset_index()
)
gender_funnel_id['viewed_rate'] = (gender_funnel_id['viewed'] / gender_funnel_id['received'] * 100).round(2)
gender_funnel_id['completed_rate'] = (gender_funnel_id['completed'] / gender_funnel_id['viewed'] * 100).round(2)
gender_funnel_id['total_rate'] = (gender_funnel_id['completed'] / gender_funnel_id['received'] * 100).round(2)
display(gender_funnel_id)

,gender,offer_type,received,viewed,completed,viewed_rate,completed_rate,total_rate
0,F,bogo,11042,9198,7501,83.30,81.55,67.93
1,F,discount,11056,7806,7976,70.60,102.18,72.14
2,M,bogo,15295,12652,7512,82.72,59.37,49.11
3,M,discount,15523,10559,8954,68.02,84.80,57.68
4,O,bogo,358,319,245,89.11,76.80,68.44
5,O,discount,371,300,256,80.86,85.33,69.00

,gender,offer_id,received,viewed,completed,viewed_rate,completed_rate,total_rate
0,F,bogo_10_10_5,2752,2637,1746,95.82,66.21,63.44
1,F,bogo_10_10_7,2773,2384,1857,85.97,77.89,66.97
2,F,bogo_5_5_5,2730,2621,1899,96.01,72.45,69.56
3,F,bogo_5_5_7,2787,1556,1999,55.83,128.47,71.73
4,F,discount_10_2_10,2719,2631,2216,96.76,84.23,81.50
5,F,discount_10_2_7,2750,1544,1851,56.15,119.88,67.31
6,F,discount_20_5_10,2852,1000,1703,35.06,170.30,59.71
7,F,discount_7_3_7,2735,2631,2206,96.20,83.85,80.66
8,M,bogo_10_10_5,3798,3648,1519,96.05,41.64,39.99
9,M,bogo_10_10_7,3869,3480,1741,89.95,50.03,45.00
10,M,bogo_5_5_5,3786,3632,2137,95.93,58.84,56.44
11,M,bogo_5_5_7,3842,1892,2115,49.25,111.79,55.05
12,M,discount_10_2_10,3918,3760,2721,95.97,72.37,69.45
13,M,discount_10_2_7,3850,1889,2000,49.06,105.88,51.95
14,M,discount_20_5_10,3880,1208,1620,31.13,134.11,41.75
15,M,discount_7_3_7,3875,3702,2613,95.54,70.58,67.43
16,O,bogo_10_10_5,72,71,45,98.61,63.38,62.50
17,O,bogo_10_10_7,94,84,59,89.36,70.24,62.77
18,O,bogo_5_5_5,89,86,67,96.63,77.91,75.28
19,O,bogo_5_5_7,103,78,74,75.73,94.87,71.84
20,O,discount_10_2_10,89,89,66,100.00,74.16,74.16
21,O,discount_10_2_7,89,66,60,74.16,90.91,67.42
22,O,discount_20_5_10,101,55,63,54.46,114.55,62.38
23,O,discount_7_3_7,92,90,67,97.83,74.44,72.83

- 여성이 남성보다 전환율이 높음
- `discount`가 `bogo`보다 전환율이 높음
- 여성에게 가장 효과적인 쿠폰은 `discount_10_2_10`(81.50%)과 `discount_7_3_7`(80.66%)
- 남성에서도 `discount_10_2_10`(81.50%)과 `discount_7_3_7`(80.66%)가 상위권임
- `discount_20_5_10`는 남녀 모두 다른 `discount` 쿠폰 대비 전환율이 낮음

20$ -> bogo, discount 둘 다 사용됨 <br>
쿠폰별 => bogo, discount completed -> 더블 카운팅 제거 -> bogo completed -> disc 누락 <br>
비용면 => 더블 카운팅 제거x -> 총합이 2개가 체크 -> 제거를 해야하고

## 2. 연령대 x 쿠폰타입 평균 결제액

In [5]:
bd_df['age_group'] = pd.cut(bd_df['age'], bins=[0, 20, 30, 40, 50, 60, 70, 100], labels=['10대', '20대', '30대', '40대', '50대', '60대', '70대+'])

# 연령대 x offer_type 퍼널 전환율
age_funnel = (
    bd_df
    .groupby(['age_group', 'offer_type'])
    .agg(
        received=('is_received', 'sum'),
        viewed=('is_viewed', 'sum'),
        completed=('is_completed', 'sum')
    )
    .reset_index()
)
age_funnel['viewed_rate'] = (age_funnel['viewed'] / age_funnel['received'] * 100).round(2)
age_funnel['completed_rate'] = (age_funnel['completed'] / age_funnel['viewed'] * 100).round(2)
age_funnel['total_rate'] = (age_funnel['completed'] / age_funnel['received'] * 100).round(2)
display(age_funnel)

# 연령대 x offer_id 퍼널 전환율
age_funnel_id = (
    bd_df
    .groupby(['age_group', 'offer_id'])
    .agg(
        received=('is_received', 'sum'),
        viewed=('is_viewed', 'sum'),
        completed=('is_completed', 'sum')
    )
    .reset_index()
)
age_funnel_id['viewed_rate'] = (age_funnel_id['viewed'] / age_funnel_id['received'] * 100).round(2)
age_funnel_id['completed_rate'] = (age_funnel_id['completed'] / age_funnel_id['viewed'] * 100).round(2)
age_funnel_id['total_rate'] = (age_funnel_id['completed'] / age_funnel_id['received'] * 100).round(2)
display(age_funnel_id)

,age_group,offer_type,received,viewed,completed,viewed_rate,completed_rate,total_rate
0,10대,bogo,640,524,244,81.88,46.56,38.12
1,10대,discount,568,335,292,58.98,87.16,51.41
2,20대,bogo,2451,1994,1066,81.35,53.46,43.49
3,20대,discount,2574,1543,1344,59.95,87.10,52.21
4,30대,bogo,2850,2353,1439,82.56,61.16,50.49
5,30대,discount,2975,1980,1754,66.55,88.59,58.96
6,40대,bogo,4337,3714,2448,85.64,65.91,56.44
7,40대,discount,4239,3088,2658,72.85,86.08,62.70
8,50대,bogo,6454,5336,3991,82.68,74.79,61.84
9,50대,discount,6553,4596,4366,70.14,95.00,66.63
10,60대,bogo,5255,4318,3130,82.17,72.49,59.56
11,60대,discount,5342,3843,3587,71.94,93.34,67.15
12,70대+,bogo,4706,3928,2938,83.47,74.80,62.43
13,70대+,discount,4685,3271,3175,69.82,97.07,67.77

,age_group,offer_id,received,viewed,completed,viewed_rate,completed_rate,total_rate
0,10대,bogo_10_10_5,166,161,44,96.99,27.33,26.51
1,10대,bogo_10_10_7,158,150,54,94.94,36.00,34.18
2,10대,bogo_5_5_5,169,162,79,95.86,48.77,46.75
3,10대,bogo_5_5_7,147,51,67,34.69,131.37,45.58
4,10대,discount_10_2_10,127,122,79,96.06,64.75,62.20
5,10대,discount_10_2_7,153,46,63,30.07,136.96,41.18
6,10대,discount_20_5_10,132,22,45,16.67,204.55,34.09
7,10대,discount_7_3_7,156,145,105,92.95,72.41,67.31
8,20대,bogo_10_10_5,640,602,195,94.06,32.39,30.47
9,20대,bogo_10_10_7,598,579,204,96.82,35.23,34.11
10,20대,bogo_5_5_5,619,593,343,95.80,57.84,55.41
11,20대,bogo_5_5_7,594,220,324,37.04,147.27,54.55
12,20대,discount_10_2_10,648,615,419,94.91,68.13,64.66
13,20대,discount_10_2_7,653,216,279,33.08,129.17,42.73
14,20대,discount_20_5_10,631,102,216,16.16,211.76,34.23
15,20대,discount_7_3_7,642,610,430,95.02,70.49,66.98
16,30대,bogo_10_10_5,661,640,274,96.82,42.81,41.45
17,30대,bogo_10_10_7,755,716,335,94.83,46.79,44.37
18,30대,bogo_5_5_5,667,641,391,96.10,61.00,58.62
19,30대,bogo_5_5_7,767,356,439,46.41,123.31,57.24
20,30대,discount_10_2_10,750,720,544,96.00,75.56,72.53
21,30대,discount_10_2_7,714,338,370,47.34,109.47,51.82
22,30대,discount_20_5_10,764,203,307,26.57,151.23,40.18
23,30대,discount_7_3_7,747,719,533,96.25,74.13,71.35
24,40대,bogo_10_10_5,1093,1054,541,96.43,51.33,49.50
25,40대,bogo_10_10_7,1115,995,624,89.24,62.71,55.96
26,40대,bogo_5_5_5,1063,1020,614,95.95,60.20,57.76
27,40대,bogo_5_5_7,1066,645,669,60.51,103.72,62.76
28,40대,discount_10_2_10,1056,1012,761,95.83,75.20,72.06
29,40대,discount_10_2_7,1067,644,609,60.36,94.57,57.08
30,40대,discount_20_5_10,1064,426,517,40.04,121.36,48.59
31,40대,discount_7_3_7,1052,1006,771,95.63,76.64,73.29
32,50대,bogo_10_10_5,1573,1508,902,95.87,59.81,57.34
33,50대,bogo_10_10_7,1618,1356,946,83.81,69.76,58.47
34,50대,bogo_5_5_5,1601,1550,1054,96.81,68.00,65.83
35,50대,bogo_5_5_7,1662,922,1089,55.48,118.11,65.52
36,50대,discount_10_2_10,1606,1552,1249,96.64,80.48,77.77
37,50대,discount_10_2_7,1637,901,1025,55.04,113.76,62.61
38,50대,discount_20_5_10,1751,637,945,36.38,148.35,53.97
39,50대,discount_7_3_7,1559,1506,1147,96.60,76.16,73.57
40,60대,bogo_10_10_5,1315,1256,688,95.51,54.78,52.32
41,60대,bogo_10_10_7,1343,1145,799,85.26,69.78,59.49
42,60대,bogo_5_5_5,1307,1241,842,94.95,67.85,64.42
43,60대,bogo_5_5_7,1290,676,801,52.40,118.49,62.09
44,60대,discount_10_2_10,1375,1332,1047,96.87,78.60,76.15
45,60대,discount_10_2_7,1320,752,851,56.97,113.16,64.47
46,60대,discount_20_5_10,1279,458,687,35.81,150.00,53.71
47,60대,discount_7_3_7,1368,1301,1002,95.10,77.02,73.25
48,70대+,bogo_10_10_5,1174,1135,666,96.68,58.68,56.73
49,70대+,bogo_10_10_7,1149,1007,695,87.64,69.02,60.49
50,70대+,bogo_5_5_5,1178,1131,779,96.01,68.88,66.13
51,70대+,bogo_5_5_7,1205,655,798,54.36,121.83,66.22
52,70대+,discount_10_2_10,1159,1122,900,96.81,80.21,77.65
53,70대+,discount_10_2_7,1141,600,710,52.59,118.33,62.23
54,70대+,discount_20_5_10,1208,414,668,34.27,161.35,55.30
55,70대+,discount_7_3_7,1177,1135,897,96.43,79.03,76.21

- 나이가 많을수록 평균 결제액이 높아짐
    - 10대는 약 12~13달러 / 50~70대는 22~24달러로 약 2배 차이
- 10~30대는 `bogo`가 70대+에서는 `discount`의 평균 결제액이 높으며 40~60대는 두개가 비슷
- `discount_20_5_10`이 전 연령대에서 평균 결제액이 가장 높음
    - 난이도가 높은 만큼 달성한 고객들의 실제 결제액도 높아지는 듯 함
- `bogo_10_10` 시리즈 도 전 연령대에서 상위권을 차지
- 고연령층 타켓에는 `discount_20_5_10`이 객단가를 높이는 데 가장 효과적이며 저연령층은 난이도가 낮은 쿠폰 위주로 접근하면 전환율 측면에서 유리할 듯 함

## 3. 소득 구간 x 쿠폰타입 달성률

In [6]:
bd_df['income_group'] = pd.cut(bd_df['income'],
    bins=[0, 40000, 60000, 80000, 100000, 120000],
    labels=['4만이하', '4~6만', '6~8만', '8~10만', '10만이상'])

# 소득 구간 x offer_type 퍼널 전환율
income_funnel = (
    bd_df
    .groupby(['income_group', 'offer_type'])
    .agg(
        received=('is_received', 'sum'),
        viewed=('is_viewed', 'sum'),
        completed=('is_completed', 'sum')
    )
    .reset_index()
)
income_funnel['viewed_rate'] = (income_funnel['viewed'] / income_funnel['received'] * 100).round(2)
income_funnel['completed_rate'] = (income_funnel['completed'] / income_funnel['viewed'] * 100).round(2)
income_funnel['total_rate'] = (income_funnel['completed'] / income_funnel['received'] * 100).round(2)
display(income_funnel)

# 소득 구간 x offer_id 퍼널 전환율
income_funnel_id = (
    bd_df
    .groupby(['income_group', 'offer_id'])
    .agg(
        received=('is_received', 'sum'),
        viewed=('is_viewed', 'sum'),
        completed=('is_completed', 'sum')
    )
    .reset_index()
)
income_funnel_id['viewed_rate'] = (income_funnel_id['viewed'] / income_funnel_id['received'] * 100).round(2)
income_funnel_id['completed_rate'] = (income_funnel_id['completed'] / income_funnel_id['viewed'] * 100).round(2)
income_funnel_id['total_rate'] = (income_funnel_id['completed'] / income_funnel_id['received'] * 100).round(2)
display(income_funnel_id)

,income_group,offer_type,received,viewed,completed,viewed_rate,completed_rate,total_rate
0,4만이하,bogo,3926,3140,1485,79.98,47.29,37.82
1,4만이하,discount,3917,2326,1893,59.38,81.38,48.33
2,4~6만,bogo,8147,6802,3995,83.49,58.73,49.04
3,4~6만,discount,8276,5605,4723,67.73,84.26,57.07
4,6~8만,bogo,8131,6913,4978,85.02,72.01,61.22
5,6~8만,discount,8344,6009,5569,72.02,92.68,66.74
6,8~10만,bogo,4647,3921,3423,84.38,87.30,73.66
7,8~10만,discount,4581,3596,3555,78.50,98.86,77.60
8,10만이상,bogo,1844,1393,1377,75.54,98.85,74.67
9,10만이상,discount,1832,1129,1446,61.63,128.08,78.93

,income_group,offer_id,received,viewed,completed,viewed_rate,completed_rate,total_rate
0,4만이하,bogo_10_10_5,947,897,242,94.72,26.98,25.55
1,4만이하,bogo_10_10_7,980,938,272,95.71,29.00,27.76
2,4만이하,bogo_5_5_5,951,899,461,94.53,51.28,48.48
3,4만이하,bogo_5_5_7,1048,406,510,38.74,125.62,48.66
4,4만이하,discount_10_2_10,978,931,609,95.19,65.41,62.27
5,4만이하,discount_10_2_7,956,314,367,32.85,116.88,38.39
6,4만이하,discount_20_5_10,1011,163,280,16.12,171.78,27.70
7,4만이하,discount_7_3_7,972,918,637,94.44,69.39,65.53
8,4~6만,bogo_10_10_5,2030,1952,800,96.16,40.98,39.41
9,4~6만,bogo_10_10_7,2045,1907,902,93.25,47.30,44.11
10,4~6만,bogo_5_5_5,2050,1966,1166,95.90,59.31,56.88
11,4~6만,bogo_5_5_7,2022,977,1127,48.32,115.35,55.74
12,4~6만,discount_10_2_10,2048,1963,1421,95.85,72.39,69.38
13,4~6만,discount_10_2_7,2059,1012,1047,49.15,103.46,50.85
14,4~6만,discount_20_5_10,2095,632,841,30.17,133.07,40.14
15,4~6만,discount_7_3_7,2074,1998,1414,96.34,70.77,68.18
16,6~8만,bogo_10_10_5,2070,1998,1142,96.52,57.16,55.17
17,6~8만,bogo_10_10_7,2040,1802,1201,88.33,66.65,58.87
18,6~8만,bogo_5_5_5,1994,1924,1288,96.49,66.94,64.59
19,6~8만,bogo_5_5_7,2027,1189,1347,58.66,113.29,66.45
20,6~8만,discount_10_2_10,2114,2055,1625,97.21,79.08,76.87
21,6~8만,discount_10_2_7,2076,1189,1319,57.27,110.93,63.54
22,6~8만,discount_20_5_10,2087,785,1080,37.61,137.58,51.75
23,6~8만,discount_7_3_7,2067,1980,1545,95.79,78.03,74.75
24,8~10만,bogo_10_10_5,1102,1063,774,96.46,72.81,70.24
25,8~10만,bogo_10_10_7,1219,967,944,79.33,97.62,77.44
26,8~10만,bogo_5_5_5,1157,1117,838,96.54,75.02,72.43
27,8~10만,bogo_5_5_7,1169,774,867,66.21,112.02,74.17
28,8~10만,discount_10_2_10,1118,1087,928,97.23,85.37,83.01
29,8~10만,discount_10_2_7,1118,791,839,70.75,106.07,75.04
30,8~10만,discount_20_5_10,1182,593,849,50.17,143.17,71.83
31,8~10만,discount_7_3_7,1163,1125,939,96.73,83.47,80.74
32,10만이상,bogo_10_10_5,473,446,352,94.29,78.92,74.42
33,10만이상,bogo_10_10_7,452,334,338,73.89,101.20,74.78
34,10만이상,bogo_5_5_5,453,433,350,95.58,80.83,77.26
35,10만이상,bogo_5_5_7,466,180,337,38.63,187.22,72.32
36,10만이상,discount_10_2_10,468,444,420,94.87,94.59,89.74
37,10만이상,discount_10_2_7,480,193,339,40.21,175.65,70.62
38,10만이상,discount_20_5_10,458,90,336,19.65,373.33,73.36
39,10만이상,discount_7_3_7,426,402,351,94.37,87.31,82.39

- 소득이 높을수록 전환율이 올라감
    - 4만 이하보다 10만 이상은 약 2배 차이가 남
- 전 소득 구간에서 `bogo`보다 `discount` 전환율이 높음
- 4만 이하에서는 `bogo_10_10` 시리즈의 전환율이 낮지만 `discount_10_2_10`(62.27%)과 `discount_7_3_7`(65.53%)은 상대적으로 높음
- 10만 이상에서는 `discount_10_2_10`(89.74%)과 `discount_7_3_7`(82.39%)이 높은 전환율을 보임
- 6~8만에서도 `discount_10_2_10`(76.87%)과 `discount_7_3_7`(74.75%)이 상위권
- `discount_20_5_10`은 난이도가 높아 저소득층에서 전환율이 매우 낮고, 소득이 올라갈수록 전환율도 올라감
- 소득 구간별 타겟 쿠폰을 다르게 설계하는 것이 효과적일듯
    - 저소득층에는 난이도가 낮은 쿠폰 위주로
    - 고소득층에는 난이도가 높은 쿠폰 위주로

## 4. 멤버십 가입 연도 x 쿠폰타입 반응률 (오래된 고객 vs 신규 고객)

In [7]:
bd_df['join_year'] = pd.to_datetime(bd_df['became_member_on']).dt.year

# 가입 연도 x offer_type 퍼널 전환율
join_funnel = (
    bd_df
    .groupby(['join_year', 'offer_type'])
    .agg(
        received=('is_received', 'sum'),
        viewed=('is_viewed', 'sum'),
        completed=('is_completed', 'sum')
    )
    .reset_index()
)
join_funnel['viewed_rate'] = (join_funnel['viewed'] / join_funnel['received'] * 100).round(2)
join_funnel['completed_rate'] = (join_funnel['completed'] / join_funnel['viewed'] * 100).round(2)
join_funnel['total_rate'] = (join_funnel['completed'] / join_funnel['received'] * 100).round(2)
display(join_funnel)

# 가입 연도 x offer_id 퍼널 전환율
join_funnel_id = (
    bd_df
    .groupby(['join_year', 'offer_id'])
    .agg(
        received=('is_received', 'sum'),
        viewed=('is_viewed', 'sum'),
        completed=('is_completed', 'sum')
    )
    .reset_index()
)
join_funnel_id['viewed_rate'] = (join_funnel_id['viewed'] / join_funnel_id['received'] * 100).round(2)
join_funnel_id['completed_rate'] = (join_funnel_id['completed'] / join_funnel_id['viewed'] * 100).round(2)
join_funnel_id['total_rate'] = (join_funnel_id['completed'] / join_funnel_id['received'] * 100).round(2)
display(join_funnel_id)

,join_year,offer_type,received,viewed,completed,viewed_rate,completed_rate,total_rate
0,2013,bogo,528,451,229,85.42,50.78,43.37
1,2013,discount,509,343,339,67.39,98.83,66.60
2,2014,bogo,1230,1029,501,83.66,48.69,40.73
3,2014,discount,1265,899,833,71.07,92.66,65.85
4,2015,bogo,3339,2805,2092,84.01,74.58,62.65
5,2015,discount,3323,2285,2397,68.76,104.90,72.13
6,2016,bogo,6302,5271,4385,83.64,83.19,69.58
7,2016,discount,6388,4597,4913,71.96,106.87,76.91
8,2017,bogo,11735,9736,6014,82.97,61.77,51.25
9,2017,discount,11609,8155,6581,70.25,80.70,56.69
10,2018,bogo,7533,6296,2448,83.58,38.88,32.50
11,2018,discount,7759,5392,2847,69.49,52.80,36.69

,join_year,offer_id,received,viewed,completed,viewed_rate,completed_rate,total_rate
0,2013,bogo_10_10_5,126,122,40,96.83,32.79,31.75
1,2013,bogo_10_10_7,140,125,44,89.29,35.20,31.43
2,2013,bogo_5_5_5,121,119,68,98.35,57.14,56.20
3,2013,bogo_5_5_7,141,85,77,60.28,90.59,54.61
4,2013,discount_10_2_10,128,121,116,94.53,95.87,90.62
5,2013,discount_10_2_7,125,70,72,56.00,102.86,57.60
6,2013,discount_20_5_10,130,32,43,24.62,134.38,33.08
7,2013,discount_7_3_7,126,120,108,95.24,90.00,85.71
8,2014,bogo_10_10_5,330,311,92,94.24,29.58,27.88
9,2014,bogo_10_10_7,304,269,88,88.49,32.71,28.95
10,2014,bogo_5_5_5,302,292,169,96.69,57.88,55.96
11,2014,bogo_5_5_7,294,157,152,53.40,96.82,51.70
12,2014,discount_10_2_10,338,327,287,96.75,87.77,84.91
13,2014,discount_10_2_7,306,188,177,61.44,94.15,57.84
14,2014,discount_20_5_10,313,94,113,30.03,120.21,36.10
15,2014,discount_7_3_7,308,290,256,94.16,88.28,83.12
16,2015,bogo_10_10_5,810,776,443,95.80,57.09,54.69
17,2015,bogo_10_10_7,844,730,483,86.49,66.16,57.23
18,2015,bogo_5_5_5,797,769,541,96.49,70.35,67.88
19,2015,bogo_5_5_7,888,530,625,59.68,117.92,70.38
20,2015,discount_10_2_10,837,807,740,96.42,91.70,88.41
21,2015,discount_10_2_7,862,482,543,55.92,112.66,62.99
22,2015,discount_20_5_10,861,277,470,32.17,169.68,54.59
23,2015,discount_7_3_7,763,719,644,94.23,89.57,84.40
24,2016,bogo_10_10_5,1586,1534,970,96.72,63.23,61.16
25,2016,bogo_10_10_7,1597,1385,1077,86.73,77.76,67.44
26,2016,bogo_5_5_5,1546,1489,1203,96.31,80.79,77.81
27,2016,bogo_5_5_7,1573,863,1135,54.86,131.52,72.16
28,2016,discount_10_2_10,1613,1569,1433,97.27,91.33,88.84
29,2016,discount_10_2_7,1605,921,1115,57.38,121.06,69.47
30,2016,discount_20_5_10,1626,615,1010,37.82,164.23,62.12
31,2016,discount_7_3_7,1544,1492,1355,96.63,90.82,87.76
32,2017,bogo_10_10_5,2945,2820,1347,95.76,47.77,45.74
33,2017,bogo_10_10_7,2897,2546,1392,87.88,54.67,48.05
34,2017,bogo_5_5_5,2971,2849,1652,95.89,57.99,55.60
35,2017,bogo_5_5_7,2922,1521,1623,52.05,106.71,55.54
36,2017,discount_10_2_10,2854,2748,1892,96.29,68.85,66.29
37,2017,discount_10_2_7,2877,1535,1485,53.35,96.74,51.62
38,2017,discount_20_5_10,2900,1002,1261,34.55,125.85,43.48
39,2017,discount_7_3_7,2978,2870,1943,96.37,67.70,65.25
40,2018,bogo_10_10_5,1826,1763,439,96.55,24.90,24.04
41,2018,bogo_10_10_7,1929,1708,604,88.54,35.36,31.31
42,2018,bogo_5_5_5,1868,1780,663,95.29,37.25,35.49
43,2018,bogo_5_5_7,1910,1045,742,54.71,71.00,38.85
44,2018,discount_10_2_10,1914,1840,849,96.13,46.14,44.36
45,2018,discount_10_2_7,1919,964,625,50.23,64.83,32.57
46,2018,discount_20_5_10,1945,691,523,35.53,75.69,26.89
47,2018,discount_7_3_7,1981,1897,850,95.76,44.81,42.91

- 2013~2016년 가입 고객은 전환율이 높고, 2017~2018년 가입 고객은 전환율이 낮음
- 전 연도에서 `discount`가 `bogo`보다 높음
- 2013~2014년 가입자가 전환율이 낮은데, 초기 멥버십 가입자 특성이 달라서 일 수도?
- `discount_10_2_10`이 전 연도에서 가장 높은 전환율을 보임
- `discount_7_3_7`도 전반적으로 높은 전환율을 보임
- 반면 `discount_20_5_10`은 낮은 전환율을 보임

---

위에랑 같이 모아서 보면 좋겠다

정상 흐름 보기 / 전체 받기 -> 정상흐름의 전환율
전체 보기 / 정상 흐름 완료 -> --

# 고객  정상 흐름

## 1. 성별x구폰타입 전환율

In [ ]:
# bogo, discount만 필터링
bd_df2 = promotion[promotion['offer_type'].isin(['bogo', 'discount'])].copy()

# 정상 흐름 여부 컬럼 추가
bd_df2['is_normal_flow'] = (
    bd_df2['offer received'].notna() &
    bd_df2['offer viewed'].notna() &
    bd_df2['offer completed'].notna() &
    (bd_df2['offer received'] <= bd_df2['offer viewed']) &
    (bd_df2['offer viewed'] <= bd_df2['offer completed'])
).astype(int)

# 성별 x offer_type
gender_offer_conversion = (
    bd_df2
    .groupby(['gender', 'offer_type'])
    .agg(total=('person', 'count'), normal_flow=('is_normal_flow', 'sum'))
    .reset_index()
)
gender_offer_conversion['normal_flow_rate'] = (
    gender_offer_conversion['normal_flow'] / gender_offer_conversion['total'] * 100
).round(2)
display(gender_offer_conversion)

# 성별 x offer_id
gender_offer_conversion_id = (
    bd_df2
    .groupby(['gender', 'offer_id'])
    .agg(total=('person', 'count'), normal_flow=('is_normal_flow', 'sum'))
    .reset_index()
)
gender_offer_conversion_id['normal_flow_rate'] = (
    gender_offer_conversion_id['normal_flow'] / gender_offer_conversion_id['total'] * 100
).round(2)
display(gender_offer_conversion_id)

  gender offer_type  total  normal_flow  normal_flow_rate
0      F       bogo  11042         5253             47.57
1      F   discount  11056         5262             47.59
2      M       bogo  15295         5276             34.49
3      M   discount  15523         6380             41.10
4      O       bogo    358          191             53.35
5      O   discount    371          199             53.64

   gender          offer_id  total  normal_flow  normal_flow_rate
0       F      bogo_10_10_5   2752         1459             53.02
1       F      bogo_10_10_7   2773         1297             46.77
2       F        bogo_5_5_5   2730         1563             57.25
3       F        bogo_5_5_7   2787          934             33.51
4       F  discount_10_2_10   2719         1908             70.17
5       F   discount_10_2_7   2750          916             33.31
6       F  discount_20_5_10   2852          617             21.63
7       F    discount_7_3_7   2735         1821             66.58
8       M      bogo_10_10_5   3798         1239             32.62
9       M      bogo_10_10_7   3869         1239             32.02
10      M        bogo_5_5_5   3786         1745             46.09
11      M        bogo_5_5_7   3842         1053             27.41
12      M  discount_10_2_10   3918         2375             60.62
13      M   discount_10_2_7   3850         1092             28.36
14      M  discount_20_5_10   3880          665             17.14
15      M    discount_7_3_7   3875         2248             58.01
16      O      bogo_10_10_5     72           40             55.56
17      O      bogo_10_10_7     94           42             44.68
18      O        bogo_5_5_5     89           60             67.42
19      O        bogo_5_5_7    103           49             47.57
20      O  discount_10_2_10     89           61             68.54
21      O   discount_10_2_7     89           44             49.44
22      O  discount_20_5_10    101           35             34.65
23      O    discount_7_3_7     92           59             64.13

In [9]:
bd_df2['age_group'] = pd.cut(bd_df2['age'], bins=[0, 20, 30, 40, 50, 60, 70, 100], labels=['10대', '20대', '30대', '40대', '50대', '60대', '70대+'])

# 연령대 x offer_type
age_offer_conversion = (
    bd_df2
    .groupby(['age_group', 'offer_type'])
    .agg(total=('person', 'count'), normal_flow=('is_normal_flow', 'sum'))
    .reset_index()
)
age_offer_conversion['normal_flow_rate'] = (
    age_offer_conversion['normal_flow'] / age_offer_conversion['total'] * 100
).round(2)
display(age_offer_conversion)

# 연령대 x offer_id
age_offer_conversion_id = (
    bd_df2
    .groupby(['age_group', 'offer_id'])
    .agg(total=('person', 'count'), normal_flow=('is_normal_flow', 'sum'))
    .reset_index()
)
age_offer_conversion_id['normal_flow_rate'] = (
    age_offer_conversion_id['normal_flow'] / age_offer_conversion_id['total'] * 100
).round(2)
display(age_offer_conversion_id)

   age_group offer_type  total  normal_flow  normal_flow_rate
0        10대       bogo    640          158             24.69
1        10대   discount    568          193             33.98
2        20대       bogo   2451          702             28.64
3        20대   discount   2574          903             35.08
4        30대       bogo   2850         1032             36.21
5        30대   discount   2975         1240             41.68
6        40대       bogo   4337         1818             41.92
7        40대   discount   4239         1970             46.47
8        50대       bogo   6454         2763             42.81
9        50대   discount   6553         2969             45.31
10       60대       bogo   5255         2198             41.83
11       60대   discount   5342         2427             45.43
12      70대+       bogo   4706         2047             43.50
13      70대+   discount   4685         2133             45.53

   age_group          offer_id  total  normal_flow  normal_flow_rate
0        10대      bogo_10_10_5    166           37             22.29
1        10대      bogo_10_10_7    158           39             24.68
2        10대        bogo_5_5_5    169           63             37.28
3        10대        bogo_5_5_7    147           19             12.93
4        10대  discount_10_2_10    127           70             55.12
5        10대   discount_10_2_7    153           25             16.34
6        10대  discount_20_5_10    132           15             11.36
7        10대    discount_7_3_7    156           83             53.21
8        20대      bogo_10_10_5    640          150             23.44
9        20대      bogo_10_10_7    598          169             28.26
10       20대        bogo_5_5_5    619          260             42.00
11       20대        bogo_5_5_7    594          123             20.71
12       20대  discount_10_2_10    648          370             57.10
13       20대   discount_10_2_7    653          112             17.15
14       20대  discount_20_5_10    631           67             10.62
15       20대    discount_7_3_7    642          354             55.14
16       30대      bogo_10_10_5    661          230             34.80
17       30대      bogo_10_10_7    755          277             36.69
18       30대        bogo_5_5_5    667          331             49.63
19       30대        bogo_5_5_7    767          194             25.29
20       30대  discount_10_2_10    750          477             63.60
21       30대   discount_10_2_7    714          202             28.29
22       30대  discount_20_5_10    764          118             15.45
23       30대    discount_7_3_7    747          443             59.30
24       40대      bogo_10_10_5   1093          463             42.36
25       40대      bogo_10_10_7   1115          454             40.72
26       40대        bogo_5_5_5   1063          510             47.98
27       40대        bogo_5_5_7   1066          391             36.68
28       40대  discount_10_2_10   1056          668             63.26
29       40대   discount_10_2_7   1067          387             36.27
30       40대  discount_20_5_10   1064          252             23.68
31       40대    discount_7_3_7   1052          663             63.02
32       50대      bogo_10_10_5   1573          743             47.23
33       50대      bogo_10_10_7   1618          631             39.00
34       50대        bogo_5_5_5   1601          864             53.97
35       50대        bogo_5_5_7   1662          525             31.59
36       50대  discount_10_2_10   1606         1078             67.12
37       50대   discount_10_2_7   1637          538             32.86
38       50대  discount_20_5_10   1751          361             20.62
39       50대    discount_7_3_7   1559          992             63.63
40       60대      bogo_10_10_5   1315          562             42.74
41       60대      bogo_10_10_7   1343          543             40.43
42       60대        bogo_5_5_5   1307          702             53.71
43       60대        bogo_5_5_7   1290          391             30.31
44       60대  discount_10_2_10   1375          912             66.33
45       60대   discount_10_2_7   1320          433             32.80
46       60대  discount_20_5_10   1279          250             19.55
47       60대    discount_7_3_7   1368          832             60.82
48      70대+      bogo_10_10_5   1174          553             47.10
49      70대+      bogo_10_10_7   1149          465             40.47
50      70대+        bogo_5_5_5   1178          637             54.07
51      70대+        bogo_5_5_7   1205          392             32.53
52      70대+  discount_10_2_10   1159          765             66.01
53      70대+   discount_10_2_7   1141          354             31.03
54      70대+  discount_20_5_10   1208          254             21.03
55      70대+    discount_7_3_7   1177          760             64.57

In [10]:
bd_df2['income_group'] = pd.cut(bd_df2['income'],
    bins=[0, 40000, 60000, 80000, 100000, 120000],
    labels=['4만이하', '4~6만', '6~8만', '8~10만', '10만이상'])

# 소득 구간 x offer_type
income_offer_conversion = (
    bd_df2
    .groupby(['income_group', 'offer_type'])
    .agg(total=('person', 'count'), normal_flow=('is_normal_flow', 'sum'))
    .reset_index()
)
income_offer_conversion['normal_flow_rate'] = (
    income_offer_conversion['normal_flow'] / income_offer_conversion['total'] * 100
).round(2)
display(income_offer_conversion)

# 소득 구간 x offer_id
income_offer_conversion_id = (
    bd_df2
    .groupby(['income_group', 'offer_id'])
    .agg(total=('person', 'count'), normal_flow=('is_normal_flow', 'sum'))
    .reset_index()
)
income_offer_conversion_id['normal_flow_rate'] = (
    income_offer_conversion_id['normal_flow'] / income_offer_conversion_id['total'] * 100
).round(2)
display(income_offer_conversion_id)

  income_group offer_type  total  normal_flow  normal_flow_rate
0         4만이하       bogo   3926          995             25.34
1         4만이하   discount   3917         1330             33.95
2         4~6만       bogo   8147         2844             34.91
3         4~6만   discount   8276         3390             40.96
4         6~8만       bogo   8131         3575             43.97
5         6~8만   discount   8344         3929             47.09
6        8~10만       bogo   4647         2417             52.01
7        8~10만   discount   4581         2412             52.65
8        10만이상       bogo   1844          889             48.21
9        10만이상   discount   1832          780             42.58

   income_group          offer_id  total  normal_flow  normal_flow_rate
0          4만이하      bogo_10_10_5    947          197             20.80
1          4만이하      bogo_10_10_7    980          236             24.08
2          4만이하        bogo_5_5_5    951          373             39.22
3          4만이하        bogo_5_5_7   1048          189             18.03
4          4만이하  discount_10_2_10    978          549             56.13
5          4만이하   discount_10_2_7    956          165             17.26
6          4만이하  discount_20_5_10   1011           83              8.21
7          4만이하    discount_7_3_7    972          533             54.84
8          4~6만      bogo_10_10_5   2030          658             32.41
9          4~6만      bogo_10_10_7   2045          707             34.57
10         4~6만        bogo_5_5_5   2050          941             45.90
11         4~6만        bogo_5_5_7   2022          538             26.61
12         4~6만  discount_10_2_10   2048         1252             61.13
13         4~6만   discount_10_2_7   2059          574             27.88
14         4~6만  discount_20_5_10   2095          355             16.95
15         4~6만    discount_7_3_7   2074         1209             58.29
16         6~8만      bogo_10_10_5   2070          954             46.09
17         6~8만      bogo_10_10_7   2040          847             41.52
18         6~8만        bogo_5_5_5   1994         1064             53.36
19         6~8만        bogo_5_5_7   2027          710             35.03
20         6~8만  discount_10_2_10   2114         1395             65.99
21         6~8만   discount_10_2_7   2076          736             35.45
22         6~8만  discount_20_5_10   2087          479             22.95
23         6~8만    discount_7_3_7   2067         1319             63.81
24        8~10만      bogo_10_10_5   1102          651             59.07
25        8~10만      bogo_10_10_7   1219          579             47.50
26        8~10만        bogo_5_5_5   1157          697             60.24
27        8~10만        bogo_5_5_7   1169          490             41.92
28        8~10만  discount_10_2_10   1118          792             70.84
29        8~10만   discount_10_2_7   1118          480             42.93
30        8~10만  discount_20_5_10   1182          352             29.78
31        8~10만    discount_7_3_7   1163          788             67.76
32        10만이상      bogo_10_10_5    473          278             58.77
33        10만이상      bogo_10_10_7    452          209             46.24
34        10만이상        bogo_5_5_5    453          293             64.68
35        10만이상        bogo_5_5_7    466          109             23.39
36        10만이상  discount_10_2_10    468          356             76.07
37        10만이상   discount_10_2_7    480           97             20.21
38        10만이상  discount_20_5_10    458           48             10.48
39        10만이상    discount_7_3_7    426          279             65.49

In [11]:
bd_df2['join_year'] = pd.to_datetime(bd_df2['became_member_on']).dt.year

# 가입 연도 x offer_type
join_offer_conversion = (
    bd_df2
    .groupby(['join_year', 'offer_type'])
    .agg(total=('person', 'count'), normal_flow=('is_normal_flow', 'sum'))
    .reset_index()
)
join_offer_conversion['normal_flow_rate'] = (
    join_offer_conversion['normal_flow'] / join_offer_conversion['total'] * 100
).round(2)
display(join_offer_conversion)

# 가입 연도 x offer_id
join_offer_conversion_id = (
    bd_df2
    .groupby(['join_year', 'offer_id'])
    .agg(total=('person', 'count'), normal_flow=('is_normal_flow', 'sum'))
    .reset_index()
)
join_offer_conversion_id['normal_flow_rate'] = (
    join_offer_conversion_id['normal_flow'] / join_offer_conversion_id['total'] * 100
).round(2)
display(join_offer_conversion_id)

    join_year offer_type  total  normal_flow  normal_flow_rate
0        2013       bogo    528          163             30.87
1        2013   discount    509          264             51.87
2        2014       bogo   1230          366             29.76
3        2014   discount   1265          647             51.15
4        2015       bogo   3339         1495             44.77
5        2015   discount   3323         1655             49.80
6        2016       bogo   6302         3131             49.68
7        2016   discount   6388         3414             53.44
8        2017       bogo  11735         4221             35.97
9        2017   discount  11609         4507             38.82
10       2018       bogo   7533         1642             21.80
11       2018   discount   7759         2014             25.96

    join_year          offer_id  total  normal_flow  normal_flow_rate
0        2013      bogo_10_10_5    126           31             24.60
1        2013      bogo_10_10_7    140           28             20.00
2        2013        bogo_5_5_5    121           55             45.45
3        2013        bogo_5_5_7    141           49             34.75
4        2013  discount_10_2_10    128          106             82.81
5        2013   discount_10_2_7    125           45             36.00
6        2013  discount_20_5_10    130           18             13.85
7        2013    discount_7_3_7    126           95             75.40
8        2014      bogo_10_10_5    330           78             23.64
9        2014      bogo_10_10_7    304           52             17.11
10       2014        bogo_5_5_5    302          151             50.00
11       2014        bogo_5_5_7    294           85             28.91
12       2014  discount_10_2_10    338          251             74.26
13       2014   discount_10_2_7    306          115             37.58
14       2014  discount_20_5_10    313           55             17.57
15       2014    discount_7_3_7    308          226             73.38
16       2015      bogo_10_10_5    810          361             44.57
17       2015      bogo_10_10_7    844          347             41.11
18       2015        bogo_5_5_5    797          452             56.71
19       2015        bogo_5_5_7    888          335             37.73
20       2015  discount_10_2_10    837          646             77.18
21       2015   discount_10_2_7    862          300             34.80
22       2015  discount_20_5_10    861          166             19.28
23       2015    discount_7_3_7    763          543             71.17
24       2016      bogo_10_10_5   1586          811             51.13
25       2016      bogo_10_10_7   1597          771             48.28
26       2016        bogo_5_5_5   1546         1001             64.75
27       2016        bogo_5_5_7   1573          548             34.84
28       2016  discount_10_2_10   1613         1249             77.43
29       2016   discount_10_2_7   1605          595             37.07
30       2016  discount_20_5_10   1626          421             25.89
31       2016    discount_7_3_7   1544         1149             74.42
32       2017      bogo_10_10_5   2945         1131             38.40
33       2017      bogo_10_10_7   2897         1001             34.55
34       2017        bogo_5_5_5   2971         1341             45.14
35       2017        bogo_5_5_7   2922          748             25.60
36       2017  discount_10_2_10   2854         1643             57.57
37       2017   discount_10_2_7   2877          749             26.03
38       2017  discount_20_5_10   2900          462             15.93
39       2017    discount_7_3_7   2978         1653             55.51
40       2018      bogo_10_10_5   1826          347             19.00
41       2018      bogo_10_10_7   1929          407             21.10
42       2018        bogo_5_5_5   1868          529             28.32
43       2018        bogo_5_5_7   1910          359             18.80
44       2018  discount_10_2_10   1914          748             39.08
45       2018   discount_10_2_7   1919          330             17.20
46       2018  discount_20_5_10   1945          214             11.00
47       2018    discount_7_3_7   1981          722             36.45