# 데이터 및 라이브러리 로드

In [97]:
import pandas as pd

In [98]:
portfolio = pd.read_csv('../data/portfolio.csv')
profile = pd.read_csv('../data/profile.csv')
transcript = pd.read_csv('../data/transcript.csv')

## 데이터 체크

In [99]:
print("[Shape]")
print("-" * 80)
print(f"portfolio : {portfolio.shape}, profile : {profile.shape}, transcript : {transcript.shape}")

print()
print("="*80)

print("\n[Info]")
print("-" * 80)
print("[portfolio]")
print(f"{portfolio.info()}")
print("\n[profile]")
print(f"{profile.info()}")
print("\n[transcript]")
print(f"{transcript.info()}")

print()
print("="*80)

print("\n[Describe]")
print("-" * 80)
print("[portfolio]")
print(f"{portfolio.describe()}")
print("\n[profile]")
print(f"{profile.describe()}")
print("\n[transcript]")
print(f"{transcript.describe()}")

[Shape]
--------------------------------------------------------------------------------
portfolio : (10, 7), profile : (17000, 6), transcript : (306534, 5)

================================================================================

[Info]
--------------------------------------------------------------------------------
[portfolio]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  10 non-null     int64
 1   reward      10 non-null     int64
 2   channels    10 non-null     object
 3   difficulty  10 non-null     int64
 4   duration    10 non-null     int64
 5   offer_type  10 non-null     object
 6   id          10 non-null     object
dtypes: int64(4), object(3)
memory usage: 692.0+ bytes
None

[profile]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        17000 non-null  int64
 1   gender            14825 non-null  object
 2   age               17000 non-null  int64
 3   id                17000 non-null  object
 4   became_member_on  17000 non-null  int64
 5   income            14825 non-null  float64
dtypes: float64(1), int64(3), object(2)
memory usage: 797.0+ KB
None

[transcript]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306534 entries, 0 to 306533
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  306534 non-null  int64
 1   person      306534 non-null  object
 2   event       306534 non-null  object
 3   value       306534 non-null  object
 4   time        306534 non-null  int64
dtypes: int64(2), object(3)
memory usage: 11.7+ MB
None

================================================================================

[Describe]
--------------------------------------------------------------------------------
[portfolio]
       Unnamed: 0     reward  difficulty   duration
count    10.00000  10.000000   10.000000  10.000000
mean      4.50000   4.200000    7.700000   6.500000
std       3.02765   3.583915    5.831905   2.321398
min       0.00000   0.000000    0.000000   3.000000
25%       2.25000   2.000000    5.000000   5.000000
50%       4.50000   4.000000    8.500000   7.000000
75%       6.75000   5.000000   10.000000   7.000000
max       9.00000  10.000000   20.000000  10.000000

[profile]
         Unnamed: 0           age  became_member_on         income
count  17000.000000  17000.000000      1.700000e+04   14825.000000
mean    8499.500000     62.531412      2.016703e+07   65404.991568
std     4907.621624     26.738580      1.167750e+04   21598.299410
min        0.000000     18.000000      2.013073e+07   30000.000000
25%     4249.750000     45.000000      2.016053e+07   49000.000000
50%     8499.500000     58.000000      2.017080e+07   64000.000000
75%    12749.250000     73.000000      2.017123e+07   80000.000000
max    16999.000000    118.000000      2.018073e+07  120000.000000

[transcript]
          Unnamed: 0           time
count  306534.000000  306534.000000
mean   153266.500000     366.382940
std     88488.888045     200.326314
min         0.000000       0.000000
25%     76633.250000     186.000000
50%    153266.500000     408.000000
75%    229899.750000     528.000000
max    306533.000000     714.000000

In [100]:
print("[Head]")
print("-" * 80)
print("[portfolio]")
display(portfolio.head())
print("[profile]")
display(profile.head())
print("[transcript]")
display(transcript.head())

[Head]
--------------------------------------------------------------------------------
[portfolio]

,Unnamed: 0,reward,channels,difficulty,duration,offer_type,id
0,0,10,"['email', 'mobile', 'social']",10,7,bogo,ae264e3637204a6fb9bb56bc8210ddfd
1,1,10,"['web', 'email', 'mobile', 'social']",10,5,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
2,2,0,"['web', 'email', 'mobile']",0,4,informational,3f207df678b143eea3cee63160fa8bed
3,3,5,"['web', 'email', 'mobile']",5,7,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
4,4,5,"['web', 'email']",20,10,discount,0b1e1539f2cc45b7b9fa7c272da2e1d7

[profile]

,Unnamed: 0,gender,age,id,became_member_on,income
0,0,NaN,118,68be06ca386d4c31939f3a4f0e3dd783,20170212,NaN
1,1,F,55,0610b486422d4921ae7d2bf64640c50b,20170715,112000.0
2,2,NaN,118,38fe809add3b4fcf9315a9694bb96ff5,20180712,NaN
3,3,F,75,78afa995795e4d85b5d9ceeca43f5fef,20170509,100000.0
4,4,NaN,118,a03223e636434f42ac4c3df47e8bac43,20170804,NaN

[transcript]

,Unnamed: 0,person,event,value,time
0,0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0
1,1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0
2,2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0
3,3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0
4,4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0

In [101]:
# 범주형 데이터 확인

# portfolio 테이블
print("[portfolio 테이블]")
print(f"{portfolio['channels'].value_counts()}")
# ['web', 'email', 'mobile', 'social']    4
# ['web', 'email', 'mobile']              3
# ['email', 'mobile', 'social']           2
# ['web', 'email']                        1
print("-"*80)

print(f"{portfolio['offer_type'].value_counts().sort_index()}")
# bogo             4
# discount         4
# informational    2
print("="*80)


# profile 테이블
print("\n[profile 테이블]")
print(f"{profile['gender'].value_counts().sort_index()}")
# F    6129
# M    8484
# O     212
print("="*80)

# transcript 테이블
print("\n[transcript 테이블]")
print(f"{transcript['event'].value_counts().sort_index()}")

[portfolio 테이블]
channels
['web', 'email', 'mobile', 'social']    4
['web', 'email', 'mobile']              3
['email', 'mobile', 'social']           2
['web', 'email']                        1
Name: count, dtype: int64
--------------------------------------------------------------------------------
offer_type
bogo             4
discount         4
informational    2
Name: count, dtype: int64
================================================================================

[profile 테이블]
gender
F    6129
M    8484
O     212
Name: count, dtype: int64
================================================================================

[transcript 테이블]
event
offer completed     33579
offer received      76277
offer viewed        57725
transaction        138953
Name: count, dtype: int64

In [102]:
# informational? 정보제공?이 이상해서 확인해봄
portfolio[portfolio['offer_type']=='informational']
# offer_type이 informational일때, difficulty와 reward가 0임을 확인. 단순 정보 제공이 맞는듯.

,Unnamed: 0,reward,channels,difficulty,duration,offer_type,id
2,2,0,"['web', 'email', 'mobile']",0,4,informational,3f207df678b143eea3cee63160fa8bed
7,7,0,"['email', 'mobile', 'social']",0,3,informational,5a8bc65990b245e5a138643cd4eb9837

### 중복값 확인

In [103]:
# 중복값 확인

print("[중복값 확인]")
print("portfolio id 개수")
print(f"{portfolio['id'].value_counts().sum()}") 
# 10 -> 고유함.

print("profile id 개수")
print(f"{profile['id'].value_counts().sum()}") 
# 17000 -> 고유함

[중복값 확인]
portfolio id 개수
10
profile id 개수
17000

### 결측치 확인

In [104]:
#portfolio
print("[portfolio 테이블]")
print(f"reward : {portfolio['reward'].isna().sum()}")
print(f"channels : {portfolio['channels'].isna().sum()}")
print(f"difficulty : {portfolio['difficulty'].isna().sum()}")
print(f"duration : {portfolio['duration'].isna().sum()}")
print(f"offer_type : {portfolio['offer_type'].isna().sum()}")
print(f"id : {portfolio['id'].isna().sum()}")
print("="*80)

#profile
print("[profile 테이블]")
print(f"gender : {profile['gender'].isna().sum()}") # 2175
print(f"age : {profile['age'].isna().sum()}")
print(f"id : {profile['id'].isna().sum()}")
print(f"became_member_on : {profile['became_member_on'].isna().sum()}")
print(f"income : {profile['income'].isna().sum()}") # 2175

#transcript
print("[transcript 테이블]")
print(f"person : {transcript['person'].isna().sum()}")
print(f"event : {transcript['event'].isna().sum()}")
print(f"value : {transcript['value'].isna().sum()}")
print(f"time : {transcript['time'].isna().sum()}")

[portfolio 테이블]
reward : 0
channels : 0
difficulty : 0
duration : 0
offer_type : 0
id : 0
================================================================================
[profile 테이블]
gender : 2175
age : 0
id : 0
became_member_on : 0
income : 2175
[transcript 테이블]
person : 0
event : 0
value : 0
time : 0