# 데이터 및 라이브러리 로드

In [2]:
import pandas as pd
import ast

In [3]:
portfolio = pd.read_csv('../data/portfolio.csv')
profile = pd.read_csv('../data/profile.csv')
transcript = pd.read_csv('../data/transcript.csv')

## 데이터 체크

In [4]:
print("[Shape]")
print("-" * 80)
print(f"portfolio : {portfolio.shape}, profile : {profile.shape}, transcript : {transcript.shape}")

print()
print("="*80)

print("\n[Info]")
print("-" * 80)
print("[portfolio]")
print(f"{portfolio.info()}")
print("\n[profile]")
print(f"{profile.info()}")
print("\n[transcript]")
print(f"{transcript.info()}")

print()
print("="*80)

print("\n[Describe]")
print("-" * 80)
print("[portfolio]")
print(f"{portfolio.describe()}")
print("\n[profile]")
print(f"{profile.describe()}")
print("\n[transcript]")
print(f"{transcript.describe()}")

[Shape]
--------------------------------------------------------------------------------
portfolio : (10, 7), profile : (17000, 6), transcript : (306534, 5)

================================================================================

[Info]
--------------------------------------------------------------------------------
[portfolio]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  10 non-null     int64
 1   reward      10 non-null     int64
 2   channels    10 non-null     object
 3   difficulty  10 non-null     int64
 4   duration    10 non-null     int64
 5   offer_type  10 non-null     object
 6   id          10 non-null     object
dtypes: int64(4), object(3)
memory usage: 692.0+ bytes
None

[profile]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Unnamed: 0        17000 non-null  int64
 1   gender            14825 non-null  object
 2   age               17000 non-null  int64
 3   id                17000 non-null  object
 4   became_member_on  17000 non-null  int64
 5   income            14825 non-null  float64
dtypes: float64(1), int64(3), object(2)
memory usage: 797.0+ KB
None

[transcript]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306534 entries, 0 to 306533
Data columns (total 5 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  306534 non-null  int64
 1   person      306534 non-null  object
 2   event       306534 non-null  object
 3   value       306534 non-null  object
 4   time        306534 non-null  int64
dtypes: int64(2), object(3)
memory usage: 11.7+ MB
None

================================================================================

[Describe]
--------------------------------------------------------------------------------
[portfolio]
       Unnamed: 0     reward  difficulty   duration
count    10.00000  10.000000   10.000000  10.000000
mean      4.50000   4.200000    7.700000   6.500000
std       3.02765   3.583915    5.831905   2.321398
min       0.00000   0.000000    0.000000   3.000000
25%       2.25000   2.000000    5.000000   5.000000
50%       4.50000   4.000000    8.500000   7.000000
75%       6.75000   5.000000   10.000000   7.000000
max       9.00000  10.000000   20.000000  10.000000

[profile]
         Unnamed: 0           age  became_member_on         income
count  17000.000000  17000.000000      1.700000e+04   14825.000000
mean    8499.500000     62.531412      2.016703e+07   65404.991568
std     4907.621624     26.738580      1.167750e+04   21598.299410
min        0.000000     18.000000      2.013073e+07   30000.000000
25%     4249.750000     45.000000      2.016053e+07   49000.000000
50%     8499.500000     58.000000      2.017080e+07   64000.000000
75%    12749.250000     73.000000      2.017123e+07   80000.000000
max    16999.000000    118.000000      2.018073e+07  120000.000000

[transcript]
          Unnamed: 0           time
count  306534.000000  306534.000000
mean   153266.500000     366.382940
std     88488.888045     200.326314
min         0.000000       0.000000
25%     76633.250000     186.000000
50%    153266.500000     408.000000
75%    229899.750000     528.000000
max    306533.000000     714.000000

In [5]:
print("[Head]")
print("-" * 80)
print("[portfolio]")
display(portfolio.head())
print("[profile]")
display(profile.head())
print("[transcript]")
display(transcript.head())

[Head]
--------------------------------------------------------------------------------
[portfolio]

,Unnamed: 0,reward,channels,difficulty,duration,offer_type,id
0,0,10,"['email', 'mobile', 'social']",10,7,bogo,ae264e3637204a6fb9bb56bc8210ddfd
1,1,10,"['web', 'email', 'mobile', 'social']",10,5,bogo,4d5c57ea9a6940dd891ad53e9dbe8da0
2,2,0,"['web', 'email', 'mobile']",0,4,informational,3f207df678b143eea3cee63160fa8bed
3,3,5,"['web', 'email', 'mobile']",5,7,bogo,9b98b8c7a33c4b65b9aebfe6a799e6d9
4,4,5,"['web', 'email']",20,10,discount,0b1e1539f2cc45b7b9fa7c272da2e1d7

[profile]

,Unnamed: 0,gender,age,id,became_member_on,income
0,0,NaN,118,68be06ca386d4c31939f3a4f0e3dd783,20170212,NaN
1,1,F,55,0610b486422d4921ae7d2bf64640c50b,20170715,112000.0
2,2,NaN,118,38fe809add3b4fcf9315a9694bb96ff5,20180712,NaN
3,3,F,75,78afa995795e4d85b5d9ceeca43f5fef,20170509,100000.0
4,4,NaN,118,a03223e636434f42ac4c3df47e8bac43,20170804,NaN

[transcript]

,Unnamed: 0,person,event,value,time
0,0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0
1,1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0
2,2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0
3,3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0
4,4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0

In [6]:
# 범주형 데이터 확인

# portfolio 테이블
print("[portfolio 테이블]")
print(f"{portfolio['channels'].value_counts()}")
# ['web', 'email', 'mobile', 'social']    4
# ['web', 'email', 'mobile']              3
# ['email', 'mobile', 'social']           2
# ['web', 'email']                        1
print("-"*80)

print(f"{portfolio['offer_type'].value_counts().sort_index()}")
# bogo             4
# discount         4
# informational    2
print("="*80)


# profile 테이블
print("\n[profile 테이블]")
print(f"{profile['gender'].value_counts().sort_index()}")
# F    6129
# M    8484
# O     212
print("="*80)

# transcript 테이블
print("\n[transcript 테이블]")
print(f"{transcript['event'].value_counts().sort_index()}")

[portfolio 테이블]
channels
['web', 'email', 'mobile', 'social']    4
['web', 'email', 'mobile']              3
['email', 'mobile', 'social']           2
['web', 'email']                        1
Name: count, dtype: int64
--------------------------------------------------------------------------------
offer_type
bogo             4
discount         4
informational    2
Name: count, dtype: int64
================================================================================

[profile 테이블]
gender
F    6129
M    8484
O     212
Name: count, dtype: int64
================================================================================

[transcript 테이블]
event
offer completed     33579
offer received      76277
offer viewed        57725
transaction        138953
Name: count, dtype: int64

In [7]:
# informational? 정보제공?이 이상해서 확인해봄
portfolio[portfolio['offer_type']=='informational']
# offer_type이 informational일때, difficulty와 reward가 0임을 확인. 단순 정보 제공이 맞는듯.

,Unnamed: 0,reward,channels,difficulty,duration,offer_type,id
2,2,0,"['web', 'email', 'mobile']",0,4,informational,3f207df678b143eea3cee63160fa8bed
7,7,0,"['email', 'mobile', 'social']",0,3,informational,5a8bc65990b245e5a138643cd4eb9837

### 중복값 확인

In [8]:
# 중복값 확인

print("[중복값 확인]")
print("portfolio id 개수")
print(f"{portfolio['id'].nunique()}") 
# 10 -> 고유함.

print("profile id 개수")
print(f"{profile['id'].nunique()}") 
# 17000 -> 고유함

print("transcript person 개수")
print(f"{transcript['person'].nunique()}")
# 17000 -> 중복값 o

[중복값 확인]
portfolio id 개수
10
profile id 개수
17000
transcript person 개수
17000

### 결측치 확인

In [9]:
#portfolio
print("[portfolio 테이블]")
print(f"reward : {portfolio['reward'].isna().sum()}")
print(f"channels : {portfolio['channels'].isna().sum()}")
print(f"difficulty : {portfolio['difficulty'].isna().sum()}")
print(f"duration : {portfolio['duration'].isna().sum()}")
print(f"offer_type : {portfolio['offer_type'].isna().sum()}")
print(f"id : {portfolio['id'].isna().sum()}")
print("="*80)

#profile
print("[profile 테이블]")
print(f"gender : {profile['gender'].isna().sum()}") # 2175
print(f"age : {profile['age'].isna().sum()}")
print(f"id : {profile['id'].isna().sum()}")
print(f"became_member_on : {profile['became_member_on'].isna().sum()}")
print(f"income : {profile['income'].isna().sum()}") # 2175

#transcript
print("[transcript 테이블]")
print(f"person : {transcript['person'].isna().sum()}")
print(f"event : {transcript['event'].isna().sum()}")
print(f"value : {transcript['value'].isna().sum()}")
print(f"time : {transcript['time'].isna().sum()}")

[portfolio 테이블]
reward : 0
channels : 0
difficulty : 0
duration : 0
offer_type : 0
id : 0
================================================================================
[profile 테이블]
gender : 2175
age : 0
id : 0
became_member_on : 0
income : 2175
[transcript 테이블]
person : 0
event : 0
value : 0
time : 0

In [ ]:
# 문자열 형태의 value 컬럼 -> 딕셔너리 형태로 변환
transcript['value'] = transcript['value'].apply(ast.literal_eval)

# 딧겨너리의 키 들을 새로운 컬럼으로 전개
value_df = pd.DataFrame(transcript['value'].tolist())
transcript = pd.concat([transcript, value_df], axis=1)

# offer id를 offer_id로 컬럼명 통일
transcript['offer_id'] = transcript['offer_id'].fillna(transcript['offer id'])
transcript = transcript.drop('offer id', axis=1)

transcript.head()

,Unnamed: 0,person,event,value,time,amount,offer_id,reward
0,0,78afa995795e4d85b5d9ceeca43f5fef,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},0,NaN,9b98b8c7a33c4b65b9aebfe6a799e6d9,NaN
1,1,a03223e636434f42ac4c3df47e8bac43,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},0,NaN,0b1e1539f2cc45b7b9fa7c272da2e1d7,NaN
2,2,e2127556f4f64592b11af22de27a7932,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},0,NaN,2906b810c7d4411798c6938adc9daaa5,NaN
3,3,8ec6ce2a7e7949b1bf142def7d0e0586,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0,NaN,fafdcd668e3743c1bb461111dcafc2a4,NaN
4,4,68617ca6246f4fbc85e91a2a49552598,offer received,{'offer id': '4d5c57ea9a6940dd891ad53e9dbe8da0'},0,NaN,4d5c57ea9a6940dd891ad53e9dbe8da0,NaN

In [ ]:
# event가 transaction일 때,
transaction = transcript[transcript['event']=='transaction'] # 138953 rows
print(f"{transaction['amount'].isna().sum()}") # 0
print(f"{transaction['offer_id'].isna().sum()}") # 138953
print(f"{transaction['reward'].isna().sum()}") # 138953

# => event가 transaction일 때, amount 생존

print("="*80)
# event가 offer recieved일 때,
offer_received = transcript[transcript['event']=='offer received'] # 76277 rows
print(f"{offer_received['amount'].isna().sum()}") # 76277
print(f"{offer_received['offer_id'].isna().sum()}") # 0
print(f"{offer_received['reward'].isna().sum()}") # 76277

# => event가 offer recieved일 때, offer_id 생존

print("="*80)
# event가 offer viewed일 때,
offer_viewed = transcript[transcript['event']=='offer viewed'] # 57725 rows
print(f"{offer_viewed['amount'].isna().sum()}") # 57725
print(f"{offer_viewed['offer_id'].isna().sum()}") # 0
print(f"{offer_viewed['reward'].isna().sum()}") # 57725

# => event가 offer viewed일 때, offer_id만 생존

print("="*80)
# event가 offer completed일 때,
offer_completed = transcript[transcript['event']=='offer completed'] # 33579 rows
print(f"{offer_completed['amount'].isna().sum()}") # 33579
print(f"{offer_completed['offer_id'].isna().sum()}") # 0
print(f"{offer_completed['reward'].isna().sum()}") # 0

# => event가 offer completed일 때, offer_id, reward(2) 생존

0
138953
138953
================================================================================
76277
0
76277
================================================================================
57725
0
57725
================================================================================
33579
0
0

In [45]:
transcript.sort_values(by=['person','time']).head(50)

,Unnamed: 0,person,event,value,time,amount,offer_id,reward
55972,55972,0009655768c64bdeb2e877511632db8f,offer received,{'offer id': '5a8bc65990b245e5a138643cd4eb9837'},168,NaN,5a8bc65990b245e5a138643cd4eb9837,NaN
77705,77705,0009655768c64bdeb2e877511632db8f,offer viewed,{'offer id': '5a8bc65990b245e5a138643cd4eb9837'},192,NaN,5a8bc65990b245e5a138643cd4eb9837,NaN
89291,89291,0009655768c64bdeb2e877511632db8f,transaction,{'amount': 22.16},228,22.16,NaN,NaN
113605,113605,0009655768c64bdeb2e877511632db8f,offer received,{'offer id': '3f207df678b143eea3cee63160fa8bed'},336,NaN,3f207df678b143eea3cee63160fa8bed,NaN
139992,139992,0009655768c64bdeb2e877511632db8f,offer viewed,{'offer id': '3f207df678b143eea3cee63160fa8bed'},372,NaN,3f207df678b143eea3cee63160fa8bed,NaN
153401,153401,0009655768c64bdeb2e877511632db8f,offer received,{'offer id': 'f19421c1d4aa40978ebb69ca19b0e20d'},408,NaN,f19421c1d4aa40978ebb69ca19b0e20d,NaN
168412,168412,0009655768c64bdeb2e877511632db8f,transaction,{'amount': 8.57},414,8.57,NaN,NaN
168413,168413,0009655768c64bdeb2e877511632db8f,offer completed,{'offer_id': 'f19421c1d4aa40978ebb69ca19b0e20d...,414,NaN,f19421c1d4aa40978ebb69ca19b0e20d,5.0
187554,187554,0009655768c64bdeb2e877511632db8f,offer viewed,{'offer id': 'f19421c1d4aa40978ebb69ca19b0e20d'},456,NaN,f19421c1d4aa40978ebb69ca19b0e20d,NaN
204340,204340,0009655768c64bdeb2e877511632db8f,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},504,NaN,fafdcd668e3743c1bb461111dcafc2a4,NaN
228422,228422,0009655768c64bdeb2e877511632db8f,transaction,{'amount': 14.11},528,14.11,NaN,NaN
228423,228423,0009655768c64bdeb2e877511632db8f,offer completed,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,528,NaN,fafdcd668e3743c1bb461111dcafc2a4,2.0
233413,233413,0009655768c64bdeb2e877511632db8f,offer viewed,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},540,NaN,fafdcd668e3743c1bb461111dcafc2a4,NaN
237784,237784,0009655768c64bdeb2e877511632db8f,transaction,{'amount': 13.56},552,13.56,NaN,NaN
247879,247879,0009655768c64bdeb2e877511632db8f,offer received,{'offer id': '2906b810c7d4411798c6938adc9daaa5'},576,NaN,2906b810c7d4411798c6938adc9daaa5,NaN
258883,258883,0009655768c64bdeb2e877511632db8f,transaction,{'amount': 10.27},576,10.27,NaN,NaN
258884,258884,0009655768c64bdeb2e877511632db8f,offer completed,{'offer_id': '2906b810c7d4411798c6938adc9daaa5...,576,NaN,2906b810c7d4411798c6938adc9daaa5,2.0
293497,293497,0009655768c64bdeb2e877511632db8f,transaction,{'amount': 12.36},660,12.36,NaN,NaN
300930,300930,0009655768c64bdeb2e877511632db8f,transaction,{'amount': 28.16},690,28.16,NaN,NaN
302205,302205,0009655768c64bdeb2e877511632db8f,transaction,{'amount': 18.41},696,18.41,NaN,NaN
56475,56475,00116118485d4dfda04fdbaba9a87b5c,offer received,{'offer id': 'f19421c1d4aa40978ebb69ca19b0e20d'},168,NaN,f19421c1d4aa40978ebb69ca19b0e20d,NaN
85769,85769,00116118485d4dfda04fdbaba9a87b5c,offer viewed,{'offer id': 'f19421c1d4aa40978ebb69ca19b0e20d'},216,NaN,f19421c1d4aa40978ebb69ca19b0e20d,NaN
104088,104088,00116118485d4dfda04fdbaba9a87b5c,transaction,{'amount': 0.7000000000000001},294,0.70,NaN,NaN
187632,187632,00116118485d4dfda04fdbaba9a87b5c,transaction,{'amount': 0.2},456,0.20,NaN,NaN
193680,193680,00116118485d4dfda04fdbaba9a87b5c,transaction,{'amount': 3.19},474,3.19,NaN,NaN
248359,248359,00116118485d4dfda04fdbaba9a87b5c,offer received,{'offer id': 'f19421c1d4aa40978ebb69ca19b0e20d'},576,NaN,f19421c1d4aa40978ebb69ca19b0e20d,NaN
284472,284472,00116118485d4dfda04fdbaba9a87b5c,offer viewed,{'offer id': 'f19421c1d4aa40978ebb69ca19b0e20d'},630,NaN,f19421c1d4aa40978ebb69ca19b0e20d,NaN
3066,3066,0011e0d4e6b944f998e987f904e8c1e5,offer received,{'offer id': '3f207df678b143eea3cee63160fa8bed'},0,NaN,3f207df678b143eea3cee63160fa8bed,NaN
16179,16179,0011e0d4e6b944f998e987f904e8c1e5,offer viewed,{'offer id': '3f207df678b143eea3cee63160fa8bed'},6,NaN,3f207df678b143eea3cee63160fa8bed,NaN
47805,47805,0011e0d4e6b944f998e987f904e8c1e5,transaction,{'amount': 13.49},132,13.49,NaN,NaN
56298,56298,0011e0d4e6b944f998e987f904e8c1e5,offer received,{'offer id': '2298d6c36e964ae4a3e7e9706d1fb8c2'},168,NaN,2298d6c36e964ae4a3e7e9706d1fb8c2,NaN
75427,75427,0011e0d4e6b944f998e987f904e8c1e5,offer viewed,{'offer id': '2298d6c36e964ae4a3e7e9706d1fb8c2'},186,NaN,2298d6c36e964ae4a3e7e9706d1fb8c2,NaN
95421,95421,0011e0d4e6b944f998e987f904e8c1e5,transaction,{'amount': 11.93},252,11.93,NaN,NaN
95422,95422,0011e0d4e6b944f998e987f904e8c1e5,offer completed,{'offer_id': '2298d6c36e964ae4a3e7e9706d1fb8c2...,252,NaN,2298d6c36e964ae4a3e7e9706d1fb8c2,3.0
113919,113919,0011e0d4e6b944f998e987f904e8c1e5,offer received,{'offer id': '5a8bc65990b245e5a138643cd4eb9837'},336,NaN,5a8bc65990b245e5a138643cd4eb9837,NaN
133370,133370,0011e0d4e6b944f998e987f904e8c1e5,offer viewed,{'offer id': '5a8bc65990b245e5a138643cd4eb9837'},354,NaN,5a8bc65990b245e5a138643cd4eb9837,NaN
153697,153697,0011e0d4e6b944f998e987f904e8c1e5,offer received,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},408,NaN,0b1e1539f2cc45b7b9fa7c272da2e1d7,NaN
177937,177937,0011e0d4e6b944f998e987f904e8c1e5,offer viewed,{'offer id': '0b1e1539f2cc45b7b9fa7c272da2e1d7'},432,NaN,0b1e1539f2cc45b7b9fa7c272da2e1d7,NaN
204643,204643,0011e0d4e6b944f998e987f904e8c1e5,offer received,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},504,NaN,9b98b8c7a33c4b65b9aebfe6a799e6d9,NaN
222679,222679,0011e0d4e6b944f998e987f904e8c1e5,offer viewed,{'offer id': '9b98b8c7a33c4b65b9aebfe6a799e6d9'},516,NaN,9b98b8c7a33c4b65b9aebfe6a799e6d9,NaN
258979,258979,0011e0d4e6b944f998e987f904e8c1e5,transaction,{'amount': 22.05},576,22.05,NaN,NaN
258980,258980,0011e0d4e6b944f998e987f904e8c1e5,offer completed,{'offer_id': '0b1e1539f2cc45b7b9fa7c272da2e1d7...,576,NaN,0b1e1539f2cc45b7b9fa7c272da2e1d7,5.0
258981,258981,0011e0d4e6b944f998e987f904e8c1e5,offer completed,{'offer_id': '9b98b8c7a33c4b65b9aebfe6a799e6d9...,576,NaN,9b98b8c7a33c4b65b9aebfe6a799e6d9,5.0
288294,288294,0011e0d4e6b944f998e987f904e8c1e5,transaction,{'amount': 23.03},642,23.03,NaN,NaN
291925,291925,0011e0d4e6b944f998e987f904e8c1e5,transaction,{'amount': 8.96},654,8.96,NaN,NaN
1889,1889,0020c2b971eb4e9188eac86d93036a77,offer received,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},0,NaN,fafdcd668e3743c1bb461111dcafc2a4,NaN
18431,18431,0020c2b971eb4e9188eac86d93036a77,offer viewed,{'offer id': 'fafdcd668e3743c1bb461111dcafc2a4'},12,NaN,fafdcd668e3743c1bb461111dcafc2a4,NaN
31326,31326,0020c2b971eb4e9188eac86d93036a77,transaction,{'amount': 17.63},54,17.63,NaN,NaN
31327,31327,0020c2b971eb4e9188eac86d93036a77,offer completed,{'offer_id': 'fafdcd668e3743c1bb461111dcafc2a4...,54,NaN,fafdcd668e3743c1bb461111dcafc2a4,2.0
34287,34287,0020c2b971eb4e9188eac86d93036a77,transaction,{'amount': 32.0},66,32.00,NaN,NaN